export enum UserMilestoneType {
    ReviewsWritten,
    MoviesReviewed,
    GamesReviewed,
    SeriesReviewed,
    BacklogAdded,
    FinishedMedia,
    SingleGenreReviewed,
    GenreVariety,
    SingleDirectorReviewed,
    DirectorVariety,
    SingleActorReviewed,
    ActorVariety,
    MonthlyReviews,
    YearlyReviews,
    ConsecutiveActivity,
}