// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MediaCritica.Server.Testing.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CommentControllerTests")]
    public partial class CommentControllerTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "CommentControllerTests.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Testing/Features", "CommentControllerTests", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Username",
                        "Forename",
                        "Surname",
                        "Email",
                        "Password",
                        "Joined"});
            table33.AddRow(new string[] {
                        "1",
                        "Username1",
                        "Test",
                        "1",
                        "test1@email.com",
                        "Password123!",
                        "2025-01-01"});
            table33.AddRow(new string[] {
                        "2",
                        "Username2",
                        "Test",
                        "2",
                        "test2@email.com",
                        "Password456!",
                        "2025-01-02"});
            table33.AddRow(new string[] {
                        "3",
                        "Username3",
                        "Test",
                        "3",
                        "test3@email.com",
                        "Password789!",
                        "2025-01-03"});
            table33.AddRow(new string[] {
                        "4",
                        "Username4",
                        "Test",
                        "4",
                        "test4@email.com",
                        "Password012!",
                        "2025-01-04"});
#line 4
 testRunner.Given("I have the following users", ((string)(null)), table33, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "UserId",
                        "Theme",
                        "Palette",
                        "Locale",
                        "Timezone"});
            table34.AddRow(new string[] {
                        "1",
                        "1",
                        "System",
                        "#000000",
                        "en-US",
                        "America/New_York"});
            table34.AddRow(new string[] {
                        "2",
                        "2",
                        "Light",
                        "#FFFFFF",
                        "en-GB",
                        "Europe/London"});
            table34.AddRow(new string[] {
                        "3",
                        "3",
                        "System",
                        "#000000",
                        "en-GB",
                        "Europe/Paris"});
            table34.AddRow(new string[] {
                        "4",
                        "4",
                        "Dark",
                        "#FFFFFF",
                        "en-US",
                        "Asia/Tokyo"});
#line 10
 testRunner.And("I have the following preferences", ((string)(null)), table34, "And ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Actors",
                        "Awards",
                        "Countries",
                        "Directors",
                        "Genres",
                        "Languages",
                        "Metascore",
                        "Plot",
                        "Poster",
                        "Rated",
                        "Released",
                        "Runtime",
                        "Title",
                        "Type",
                        "Writers",
                        "Year",
                        "ImdbRating",
                        "ImdbVotes",
                        "BoxOffice",
                        "DVD",
                        "Website",
                        "Production"});
            table35.AddRow(new string[] {
                        "1",
                        "Actor 1, Actor 2",
                        "Award 1",
                        "USA, UK",
                        "Director 1, Director 2",
                        "Action, Drama",
                        "English",
                        "85",
                        "A great plot",
                        "Media Poster 1",
                        "PG-13",
                        "2020-02-03",
                        "120 min",
                        "Media Title 1",
                        "movie",
                        "Writer 1",
                        "2020",
                        "8.5",
                        "1500",
                        "$300,000,000",
                        "",
                        "",
                        ""});
#line 16
 testRunner.And("I have the following movies", ((string)(null)), table35, "And ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "MediaId",
                        "MediaPoster",
                        "MediaTitle",
                        "MediaType",
                        "UserId",
                        "ReviewerUsername",
                        "Rating",
                        "Title",
                        "Description",
                        "Date"});
            table36.AddRow(new string[] {
                        "1",
                        "1",
                        "Media Poster 1",
                        "Media Title 1",
                        "movie",
                        "3",
                        "Username3",
                        "4",
                        "Test Title",
                        "Test Description",
                        "2025-01-01"});
#line 19
 testRunner.And("I have the following reviews", ((string)(null)), table36, "And ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "ReviewId",
                        "ParentId",
                        "Content",
                        "CommenterId",
                        "CommenterName",
                        "CommentedAt",
                        "Status"});
            table37.AddRow(new string[] {
                        "1",
                        "1",
                        "<null>",
                        "Comment 1",
                        "1",
                        "Test 1",
                        "2025-01-27 14:05:45",
                        "Active"});
            table37.AddRow(new string[] {
                        "2",
                        "1",
                        "1",
                        "Comment 2",
                        "2",
                        "Test 2",
                        "2025-01-28 15:02:02",
                        "Active"});
            table37.AddRow(new string[] {
                        "3",
                        "1",
                        "<null>",
                        "Comment 3",
                        "1",
                        "Test 1",
                        "2025-01-29 14:12:39",
                        "Active"});
            table37.AddRow(new string[] {
                        "4",
                        "1",
                        "3",
                        "Comment 4",
                        "4",
                        "Test 4",
                        "2025-01-29 17:36:05",
                        "Active"});
            table37.AddRow(new string[] {
                        "5",
                        "1",
                        "3",
                        "Comment 5",
                        "1",
                        "Test 1",
                        "2025-01-30 01:54:56",
                        "Active"});
            table37.AddRow(new string[] {
                        "6",
                        "1",
                        "3",
                        "Comment 6",
                        "1",
                        "Test 1",
                        "2025-01-30 03:40:37",
                        "Active"});
            table37.AddRow(new string[] {
                        "7",
                        "1",
                        "5",
                        "Comment 7",
                        "2",
                        "Test 2",
                        "2025-01-31 03:37:54",
                        "Active"});
            table37.AddRow(new string[] {
                        "8",
                        "1",
                        "5",
                        "Comment 8",
                        "4",
                        "Test 4",
                        "2025-02-01 12:48:36",
                        "Removed"});
#line 22
 testRunner.And("I have the following comments", ((string)(null)), table37, "And ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "CommentId",
                        "ReporterId",
                        "Reason",
                        "Details",
                        "ReportedAt"});
            table38.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "Spam",
                        "Spam Comment",
                        "2025-02-20"});
#line 32
 testRunner.And("I have the following reports", ((string)(null)), table38, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get review comments")]
        public void GetReviewComments()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get review comments", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 37
    testRunner.When("I call GetReviewComments with the review id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
    testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ReviewId",
                            "ParentId",
                            "Content",
                            "CommenterId",
                            "CommenterName",
                            "CommentedAt",
                            "TotalReplies"});
                table39.AddRow(new string[] {
                            "3",
                            "1",
                            "<null>",
                            "Comment 3",
                            "1",
                            "Test 1",
                            "2025-01-29",
                            "3"});
                table39.AddRow(new string[] {
                            "6",
                            "1",
                            "3",
                            "Comment 6",
                            "1",
                            "Test 1",
                            "2025-01-30",
                            "0"});
                table39.AddRow(new string[] {
                            "5",
                            "1",
                            "3",
                            "Comment 5",
                            "1",
                            "Test 1",
                            "2025-01-30",
                            "1"});
                table39.AddRow(new string[] {
                            "7",
                            "1",
                            "5",
                            "Comment 7",
                            "2",
                            "Test 2",
                            "2025-01-31",
                            "0"});
                table39.AddRow(new string[] {
                            "1",
                            "1",
                            "<null>",
                            "Comment 1",
                            "1",
                            "Test 1",
                            "2025-01-27",
                            "1"});
                table39.AddRow(new string[] {
                            "2",
                            "1",
                            "1",
                            "Comment 2",
                            "2",
                            "Test 2",
                            "2025-01-28",
                            "0"});
#line 39
    testRunner.And("The returned comments structure should match the expected hierarchy:", ((string)(null)), table39, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get review comments for a review that doesn\'t exist")]
        public void GetReviewCommentsForAReviewThatDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get review comments for a review that doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 49
 testRunner.When("I call GetReviewComments with the review id 99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 50
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
 testRunner.And("The response should be \"Review Not Found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get comments remaining children")]
        public void GetCommentsRemainingChildren()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get comments remaining children", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 54
 testRunner.When("I call GetCommentsRemainingChildren with the comment id 3 and offset 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ReviewId",
                            "ParentId",
                            "Content",
                            "CommenterId",
                            "CommenterUsername",
                            "CommentedAt",
                            "TotalReplies"});
                table40.AddRow(new string[] {
                            "4",
                            "1",
                            "3",
                            "Comment 4",
                            "4",
                            "Username4",
                            "28 days ago",
                            "0"});
#line 56
 testRunner.And("The CommentModels should be", ((string)(null)), table40, "And ");
#line hidden
#line 59
 testRunner.And("The children should be empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Post a comment")]
        public void PostAComment()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post a comment", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                            "ReviewId",
                            "ParentId",
                            "Content",
                            "CommenterId",
                            "CommenterName"});
                table41.AddRow(new string[] {
                            "1",
                            "1",
                            "New Comment",
                            "1",
                            "Test 1"});
#line 62
 testRunner.When("I call PostComment with the following data", ((string)(null)), table41, "When ");
#line hidden
#line 65
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ReviewId",
                            "ParentId",
                            "Content",
                            "CommenterId",
                            "CommenterUsername",
                            "CommentedAt",
                            "TotalReplies"});
                table42.AddRow(new string[] {
                            "9",
                            "1",
                            "1",
                            "New Comment",
                            "1",
                            "Username1",
                            "just now",
                            "0"});
#line 66
 testRunner.And("The CommentModel should be", ((string)(null)), table42, "And ");
#line hidden
#line 69
 testRunner.And("The children should be empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Post a comment but the user doesn\'t exist")]
        public void PostACommentButTheUserDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post a comment but the user doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                            "ReviewId",
                            "ParentId",
                            "Content",
                            "CommenterId",
                            "CommenterName"});
                table43.AddRow(new string[] {
                            "1",
                            "1",
                            "New Comment",
                            "99",
                            "Test 1"});
#line 72
 testRunner.When("I call PostComment with the following data", ((string)(null)), table43, "When ");
#line hidden
#line 75
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 76
 testRunner.And("The response should be \"User Not Found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Post a comment but the parent doesn\'t exist")]
        public void PostACommentButTheParentDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post a comment but the parent doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                            "ReviewId",
                            "ParentId",
                            "Content",
                            "CommenterId",
                            "CommenterName"});
                table44.AddRow(new string[] {
                            "1",
                            "99",
                            "New Comment",
                            "1",
                            "Test 1"});
#line 79
 testRunner.When("I call PostComment with the following data", ((string)(null)), table44, "When ");
#line hidden
#line 82
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 83
 testRunner.And("The response should be \"Parent Comment Not Found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Post a comment but the parent is not active")]
        public void PostACommentButTheParentIsNotActive()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post a comment but the parent is not active", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                            "ReviewId",
                            "ParentId",
                            "Content",
                            "CommenterId",
                            "CommenterName"});
                table45.AddRow(new string[] {
                            "1",
                            "8",
                            "New Comment",
                            "1",
                            "Test 1"});
#line 86
 testRunner.When("I call PostComment with the following data", ((string)(null)), table45, "When ");
#line hidden
#line 89
 testRunner.Then("The status code should be 409", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 90
 testRunner.And("The response should be \"Cannot reply to a deleted comment\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update a comment")]
        public void UpdateAComment()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update a comment", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content"});
                table46.AddRow(new string[] {
                            "1",
                            "Updated Comment"});
#line 93
 testRunner.When("I call UpdateComment with the following data", ((string)(null)), table46, "When ");
#line hidden
#line 96
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 97
 testRunner.And("The response should be \"Comment Updated\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update a comment that doesn\'t exist")]
        public void UpdateACommentThatDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update a comment that doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 99
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content"});
                table47.AddRow(new string[] {
                            "99",
                            "Updated Comment"});
#line 100
 testRunner.When("I call UpdateComment with the following data", ((string)(null)), table47, "When ");
#line hidden
#line 103
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 104
 testRunner.And("The response should be \"Comment Not Found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Report a comment")]
        public void ReportAComment()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report a comment", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 106
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentId",
                            "ReporterId",
                            "Reason",
                            "Details"});
                table48.AddRow(new string[] {
                            "1",
                            "1",
                            "Spam",
                            "Spam Comment"});
#line 107
 testRunner.When("I call ReportComment with the following data", ((string)(null)), table48, "When ");
#line hidden
#line 110
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 111
 testRunner.And("The response should be \"Comment Reported\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CommentId",
                            "ReporterId",
                            "Reason",
                            "Details",
                            "ReportedAt"});
                table49.AddRow(new string[] {
                            "2",
                            "1",
                            "1",
                            "Spam",
                            "Spam Comment",
                            "2025-02-27 16:30:00"});
#line 112
 testRunner.And("The following report should be in the database", ((string)(null)), table49, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Report a comment that a user has already reported")]
        public void ReportACommentThatAUserHasAlreadyReported()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report a comment that a user has already reported", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 116
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentId",
                            "ReporterId",
                            "Reason",
                            "Details"});
                table50.AddRow(new string[] {
                            "1",
                            "2",
                            "Spam",
                            "Spam Comment"});
#line 117
 testRunner.When("I call ReportComment with the following data", ((string)(null)), table50, "When ");
#line hidden
#line 120
 testRunner.Then("The status code should be 409", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 121
 testRunner.And("The response should be \"Comment Already Reported\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Report a comment that doesn\'t exist")]
        public void ReportACommentThatDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report a comment that doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 123
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentId",
                            "ReporterId",
                            "Reason",
                            "Details"});
                table51.AddRow(new string[] {
                            "99",
                            "1",
                            "Spam",
                            "Spam Comment"});
#line 124
 testRunner.When("I call ReportComment with the following data", ((string)(null)), table51, "When ");
#line hidden
#line 127
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 128
 testRunner.And("The response should be \"Comment Not Found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Report a comment with an invalid user")]
        public void ReportACommentWithAnInvalidUser()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report a comment with an invalid user", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 130
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                            "CommentId",
                            "ReporterId",
                            "Reason",
                            "Details"});
                table52.AddRow(new string[] {
                            "1",
                            "99",
                            "Spam",
                            "Spam Comment"});
#line 131
 testRunner.When("I call ReportComment with the following data", ((string)(null)), table52, "When ");
#line hidden
#line 134
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 135
 testRunner.And("The response should be \"User Not Found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
