// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MediaCritica.Server.Testing.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ReviewControllerTests")]
    public partial class ReviewControllerTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "ReviewControllerTests.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Testing/Features", "ReviewControllerTests", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
            TechTalk.SpecFlow.Table table148 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Username",
                        "Forename",
                        "Surname",
                        "Email",
                        "Password",
                        "Joined"});
            table148.AddRow(new string[] {
                        "1",
                        "Username1",
                        "Test",
                        "1",
                        "test1@email.com",
                        "Password123!",
                        "2025-01-01"});
            table148.AddRow(new string[] {
                        "2",
                        "Username2",
                        "Test",
                        "2",
                        "test2@email.com",
                        "Password456!",
                        "2025-01-02"});
            table148.AddRow(new string[] {
                        "3",
                        "Username3",
                        "Test",
                        "3",
                        "test3@email.com",
                        "Password789!",
                        "2025-01-03"});
            table148.AddRow(new string[] {
                        "4",
                        "Username4",
                        "Test",
                        "4",
                        "test4@email.com",
                        "Password012!",
                        "2025-01-04"});
#line 4
 testRunner.Given("I have the following users", ((string)(null)), table148, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table149 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Actors",
                        "Awards",
                        "Countries",
                        "Directors",
                        "Genres",
                        "Languages",
                        "Metascore",
                        "Plot",
                        "Poster",
                        "Rated",
                        "Released",
                        "Runtime",
                        "Title",
                        "Type",
                        "Writers",
                        "Year",
                        "ImdbRating",
                        "ImdbVotes",
                        "BoxOffice",
                        "DVD",
                        "Website",
                        "Production"});
            table149.AddRow(new string[] {
                        "1",
                        "Actor 1, Actor 2",
                        "Award 1",
                        "USA, UK",
                        "Director 1, Director 2",
                        "Action, Drama",
                        "English",
                        "85",
                        "A great plot",
                        "Media Poster 1",
                        "PG-13",
                        "2020-02-03",
                        "120 min",
                        "Media Title 1",
                        "movie",
                        "Writer 1",
                        "2020",
                        "8.5",
                        "1500",
                        "$300,000,000",
                        "",
                        "",
                        ""});
#line 10
 testRunner.And("I have the following movies", ((string)(null)), table149, "And ");
#line hidden
            TechTalk.SpecFlow.Table table150 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "MediaId",
                        "MediaPoster",
                        "MediaTitle",
                        "MediaType",
                        "UserId",
                        "ReviewerUsername",
                        "Rating",
                        "Title",
                        "Description",
                        "Date"});
            table150.AddRow(new string[] {
                        "1",
                        "1",
                        "Media Poster 1",
                        "Media Title 1",
                        "movie",
                        "3",
                        "Username3",
                        "4",
                        "Test Title",
                        "Test Description",
                        "2025-01-01"});
#line 13
 testRunner.And("I have the following reviews", ((string)(null)), table150, "And ");
#line hidden
            TechTalk.SpecFlow.Table table151 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "ReviewId",
                        "ReporterId",
                        "Reason",
                        "Details",
                        "ReportedAt"});
            table151.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "Spam",
                        "Spam Comment",
                        "2025-02-20"});
#line 16
 testRunner.And("I have the following reports", ((string)(null)), table151, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get a review by id")]
        public void GetAReviewById()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a review by id", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 21
 testRunner.When("I call GetReview with id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table152 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Date",
                            "Description",
                            "MediaType",
                            "MediaId",
                            "MediaPoster",
                            "MediaTitle",
                            "MediaSeriesId",
                            "MediaSeriesTitle",
                            "MediaEpisode",
                            "Rating",
                            "ReviewerId",
                            "ReviewerUsername",
                            "Title",
                            "Likes",
                            "Dislikes"});
                table152.AddRow(new string[] {
                            "1",
                            "1 month ago",
                            "Test Description",
                            "movie",
                            "1",
                            "Media Poster 1",
                            "Media Title 1",
                            "<null>",
                            "<null>",
                            "<null>",
                            "4",
                            "3",
                            "Username3",
                            "Test Title",
                            "0",
                            "0"});
#line 23
 testRunner.And("The ReviewModel should be", ((string)(null)), table152, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get a review by id that doesn\'t exist")]
        public void GetAReviewByIdThatDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a review by id that doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 28
 testRunner.When("I call GetReview with id 10", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
 testRunner.And("The response should be \"Review not found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get a user reviews")]
        public void GetAUserReviews()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a user reviews", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 33
 testRunner.When("I call GetUserReviews", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get a media reviews")]
        public void GetAMediaReviews()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a media reviews", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 37
 testRunner.When("I call GetMediaReviews with the media id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Post a review")]
        public void PostAReview()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post a review", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table153 = new TechTalk.SpecFlow.Table(new string[] {
                            "Date",
                            "Description",
                            "MediaType",
                            "MediaId",
                            "MediaPoster",
                            "MediaTitle",
                            "MediaSeriesId",
                            "MediaSeriesTitle",
                            "MediaEpisode",
                            "Rating",
                            "ReviewerId",
                            "ReviewerUsername",
                            "Title"});
                table153.AddRow(new string[] {
                            "2025-02-02",
                            "Test Description 2",
                            "movie",
                            "1",
                            "Media Poster 1",
                            "Media Title 1",
                            "<null>",
                            "<null>",
                            "<null>",
                            "3",
                            "1",
                            "Username1",
                            "Test Title"});
#line 41
 testRunner.When("I call PostReview with the following data", ((string)(null)), table153, "When ");
#line hidden
#line 44
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
 testRunner.And("The response should be 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Post a review but the user doesn\'t exist")]
        public void PostAReviewButTheUserDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post a review but the user doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table154 = new TechTalk.SpecFlow.Table(new string[] {
                            "Date",
                            "Description",
                            "MediaType",
                            "MediaId",
                            "MediaPoster",
                            "MediaTitle",
                            "MediaSeriesId",
                            "MediaSeriesTitle",
                            "MediaEpisode",
                            "Rating",
                            "ReviewerId",
                            "ReviewerUsername",
                            "Title"});
                table154.AddRow(new string[] {
                            "2025-02-02",
                            "Test Description 2",
                            "movie",
                            "1",
                            "Media Poster 1",
                            "Media Title 1",
                            "<null>",
                            "<null>",
                            "<null>",
                            "5",
                            "10",
                            "Username10",
                            "Test Title"});
#line 48
 testRunner.When("I call PostReview with the following data", ((string)(null)), table154, "When ");
#line hidden
#line 51
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
 testRunner.And("The response should be \"User not found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Post a review but the media doesn\'t exist")]
        public void PostAReviewButTheMediaDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post a review but the media doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table155 = new TechTalk.SpecFlow.Table(new string[] {
                            "Date",
                            "Description",
                            "MediaType",
                            "MediaId",
                            "MediaPoster",
                            "MediaTitle",
                            "MediaSeriesId",
                            "MediaSeriesTitle",
                            "MediaEpisode",
                            "Rating",
                            "ReviewerId",
                            "ReviewerUsername",
                            "Title"});
                table155.AddRow(new string[] {
                            "2025-02-02",
                            "Test Description 2",
                            "movie",
                            "2",
                            "Media Poster 2",
                            "Media Title 2",
                            "<null>",
                            "<null>",
                            "<null>",
                            "3",
                            "1",
                            "Username1",
                            "Test Title"});
#line 55
 testRunner.When("I call PostReview with the following data", ((string)(null)), table155, "When ");
#line hidden
#line 58
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
 testRunner.And("The response should be \"Media not found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Post a review that a user has already reviewed")]
        public void PostAReviewThatAUserHasAlreadyReviewed()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post a review that a user has already reviewed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table156 = new TechTalk.SpecFlow.Table(new string[] {
                            "Date",
                            "Description",
                            "MediaType",
                            "MediaId",
                            "MediaPoster",
                            "MediaTitle",
                            "MediaSeriesId",
                            "MediaSeriesTitle",
                            "MediaEpisode",
                            "Rating",
                            "ReviewerId",
                            "ReviewerUsername",
                            "Title"});
                table156.AddRow(new string[] {
                            "2025-02-02",
                            "Test Description 2",
                            "movie",
                            "1",
                            "Media Poster 1",
                            "Media Title 1",
                            "<null>",
                            "<null>",
                            "<null>",
                            "4.5",
                            "3",
                            "Username1",
                            "Test Title"});
#line 62
 testRunner.When("I call PostReview with the following data", ((string)(null)), table156, "When ");
#line hidden
#line 65
 testRunner.Then("The status code should be 409", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 66
 testRunner.And("The response should be \"User has already reviewed this media\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update a review")]
        public void UpdateAReview()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update a review", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table157 = new TechTalk.SpecFlow.Table(new string[] {
                            "ReviewId",
                            "Title",
                            "Description",
                            "Rating"});
                table157.AddRow(new string[] {
                            "1",
                            "Updated Title",
                            "Updated Description",
                            "1"});
#line 69
 testRunner.When("I call UpdateReview with the following data", ((string)(null)), table157, "When ");
#line hidden
#line 72
testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table158 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Date",
                            "Description",
                            "MediaType",
                            "MediaId",
                            "MediaPoster",
                            "MediaTitle",
                            "MediaSeriesId",
                            "MediaSeriesTitle",
                            "MediaEpisode",
                            "Rating",
                            "ReviewerId",
                            "ReviewerUsername",
                            "Title",
                            "Likes",
                            "Dislikes"});
                table158.AddRow(new string[] {
                            "1",
                            "just now",
                            "Updated Description",
                            "movie",
                            "1",
                            "Media Poster 1",
                            "Media Title 1",
                            "<null>",
                            "<null>",
                            "<null>",
                            "1",
                            "3",
                            "Username3",
                            "Updated Title",
                            "0",
                            "0"});
#line 73
 testRunner.And("The ReviewModel should be", ((string)(null)), table158, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update a review that doesn\'t exist")]
        public void UpdateAReviewThatDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update a review that doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table159 = new TechTalk.SpecFlow.Table(new string[] {
                            "ReviewId",
                            "Title",
                            "Description",
                            "Rating"});
                table159.AddRow(new string[] {
                            "10",
                            "Updated Title",
                            "Updated Description",
                            "1"});
#line 78
 testRunner.When("I call UpdateReview with the following data", ((string)(null)), table159, "When ");
#line hidden
#line 81
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 82
 testRunner.And("The response should be \"Review not found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete a review")]
        public void DeleteAReview()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete a review", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 85
 testRunner.When("I call delete review with id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 86
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 87
 testRunner.And("The response should be \"Review Deleted\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete a review that doesn\'t exist")]
        public void DeleteAReviewThatDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete a review that doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 89
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 90
 testRunner.When("I call delete review with id 10", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 91
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 92
 testRunner.And("The response should be \"Review not found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get a users review status that is true")]
        public void GetAUsersReviewStatusThatIsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a users review status that is true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 94
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table160 = new TechTalk.SpecFlow.Table(new string[] {
                            "Username",
                            "Password",
                            "RememberMe"});
                table160.AddRow(new string[] {
                            "Username3",
                            "Password789!",
                            "false"});
#line 95
 testRunner.Given("I am the following user", ((string)(null)), table160, "Given ");
#line hidden
#line 98
 testRunner.When("I call GetUserReviewStatus with media id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 99
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 100
 testRunner.And("The response should be true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get a users review status that is false")]
        public void GetAUsersReviewStatusThatIsFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a users review status that is false", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 102
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table161 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RememberMe"});
                table161.AddRow(new string[] {
                            "test2@email.com",
                            "Password456!",
                            "false"});
#line 103
 testRunner.Given("I am the following user", ((string)(null)), table161, "Given ");
#line hidden
#line 106
 testRunner.When("I call GetUserReviewStatus with media id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 107
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 108
 testRunner.And("The response should be false", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Report a review")]
        public void ReportAReview()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report a review", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 110
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table162 = new TechTalk.SpecFlow.Table(new string[] {
                            "ReviewId",
                            "ReporterId",
                            "Reason",
                            "Details"});
                table162.AddRow(new string[] {
                            "1",
                            "1",
                            "Hate",
                            "Hate Comment"});
#line 111
 testRunner.When("I call ReportReview with the following data", ((string)(null)), table162, "When ");
#line hidden
#line 114
 testRunner.Then("The status code should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 115
 testRunner.And("The response should be \"Review Reported\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table163 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ReviewId",
                            "ReporterId",
                            "Reason",
                            "Details",
                            "ReportedAt"});
                table163.AddRow(new string[] {
                            "2",
                            "1",
                            "1",
                            "Hate",
                            "Hate Comment",
                            "2025-02-27 16:30:00"});
#line 116
 testRunner.And("The following report should be in the database", ((string)(null)), table163, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Report a review that a user has already reported")]
        public void ReportAReviewThatAUserHasAlreadyReported()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report a review that a user has already reported", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 120
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table164 = new TechTalk.SpecFlow.Table(new string[] {
                            "ReviewId",
                            "ReporterId",
                            "Reason",
                            "Details"});
                table164.AddRow(new string[] {
                            "1",
                            "2",
                            "Spam",
                            "Spam Comment"});
#line 121
 testRunner.When("I call ReportReview with the following data", ((string)(null)), table164, "When ");
#line hidden
#line 124
 testRunner.Then("The status code should be 409", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 125
 testRunner.And("The response should be \"Review Already Reported\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Report a review that doesn\'t exist")]
        public void ReportAReviewThatDoesntExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report a review that doesn\'t exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 127
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table165 = new TechTalk.SpecFlow.Table(new string[] {
                            "ReviewId",
                            "ReporterId",
                            "Reason",
                            "Details"});
                table165.AddRow(new string[] {
                            "99",
                            "1",
                            "Hate",
                            "Hate Comment"});
#line 128
 testRunner.When("I call ReportReview with the following data", ((string)(null)), table165, "When ");
#line hidden
#line 131
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 132
 testRunner.And("The response should be \"Review Not Found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Report a review with an invalid user")]
        public void ReportAReviewWithAnInvalidUser()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report a review with an invalid user", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 134
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table166 = new TechTalk.SpecFlow.Table(new string[] {
                            "ReviewId",
                            "ReporterId",
                            "Reason",
                            "Details"});
                table166.AddRow(new string[] {
                            "1",
                            "99",
                            "Hate",
                            "Hate Comment"});
#line 135
 testRunner.When("I call ReportReview with the following data", ((string)(null)), table166, "When ");
#line hidden
#line 138
 testRunner.Then("The status code should be 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 139
 testRunner.And("The response should be \"User Not Found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
