@MediaCritica.Server_HostAddress = http://localhost:5227

GET {{MediaCritica.Server_HostAddress}}/User/GetUser/
Accept: application/json

###

POST {{MediaCritica.Server_HostAddress}}/User/PostUser
Accept: application/json

###

PUT {{MediaCritica.Server_HostAddress}}/User/UpdateUser
Accept: application/json

###

DELETE {{MediaCritica.Server_HostAddress}}/User/DeleteUser
Accept: application/json

###

PUT {{MediaCritica.Server_HostAddress}}/User/UpdateUserPreference
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetMediaBySearch/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetExploreMediaBySearch/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetExploreMedia/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetBestOfPrevYear/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetBestOfCurYear/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetBestOfAllTime/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetUpcoming/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetLatest/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetSeasonalPicks/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetMostReviewed/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetRecentlyReviewed/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetMovie/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetSeries/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetSeason/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetGame/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Media/GetEpisode/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Review/GetReview/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Review/GetUserReviews/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Review/GetMediaReviews/
Accept: application/json

###

POST {{MediaCritica.Server_HostAddress}}/Review/PostReview
Accept: application/json

###

PUT {{MediaCritica.Server_HostAddress}}/Review/UpdateReview
Accept: application/json

###

DELETE {{MediaCritica.Server_HostAddress}}/Review/DeleteReview/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Backlog/GetBacklog/
Accept: application/json

###

POST {{MediaCritica.Server_HostAddress}}/Backlog/PostBacklog
Accept: application/json

###

DELETE {{MediaCritica.Server_HostAddress}}/Backlog/DeleteBacklog/
Accept: application/json

###

PUT {{MediaCritica.Server_HostAddress}}/Backlog/UpdateBacklogState/
Accept: application/json

###

GET {{MediaCritica.Server_HostAddress}}/Leaderboards/GetUserRankings/
Accept: application/json




